# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs submodule update
      - name: Submodule update
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin master

      # Install Hugo
      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.67.1/hugo_extended_0.67.1_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.67.1_Linux-64bit.deb
          
      # Run & build Hugo
      - name: Run and build Hugo
        run: |
          mkdir -p common/content/conversion
          cp -r java common/content/conversion
          cp -r net common/content/conversion
          cp _index.md common/content/conversion
          hugo --source common --minify --config config.toml,ignore-total-config.toml
          cd common/public
          zip -r -q conversion.zip conversion
