# Deploy documentation to the server

name: Deploy

# Start deploy after build is finished
on:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy sitemap
        run: ls -l
        #uses: nogsantos/scp-deploy@master
        #with:
          #src: product-sitemap.xml
          #host: ${{ secrets.DOCS_SSH_HOST }}
          #remote: ${{ secrets.DOCS_SSH_DIR }}/sitemaps/test.xml
          #user: ${{ secrets.DOCS_SSH_USER }}
          #key: ${{ secrets.DOCS_SSH_KEY }}
        
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@v2
      - name: Failed
        run: Deploy has failed!
